### ISSUE TITLE
Get working with more recent GHC versions

### ISSUE THREAD

**Issue by bjpop** [bjpop/ministg#3]
From a ministg user:

Two small fixes were required to apparently accommodate recent module factoring:
In Utils.hs add
 import Control.Exception(catch,IOException)
and change
 show error
to
 show (error :: IOException)

**Comment by andreabedini** [comment]
Hi @bjpop,
ministg seems to work fine on new GHC versions (I tested 8.8.1 and 8.6.5). I also have done some [small tweaks](https://github.com/bjpop/ministg/compare/master...andreabedini:master) in my fork if you are interested. The main change is allowing to load multiple files at once, which I find it to be a better way to load the prelude. Thanks for the project!

**Comment by bjpop** [comment]
Hi @andreabedini. Small tweaks would be appreciated. I would happily consider a pull request if you have time. Cheers!

**Comment by andreabedini** [comment]
See #6

**Comment by bjpop** [comment]
This is fixed now.
